[build]
  base    = "myapp"
  command = "bash -lc 'echo Building with API_BASE=$API_BASE && echo \"window.API_BASE=\\\"$API_BASE\\\";\" > runtime-config.js && npm ci && npm run build'"
  publish = "dist"

[build.environment]
  API_BASE = ""   # actual value is set in Netlify UI

[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy        = "no-referrer"
  X-Frame-Options        = "DENY"
