[build]
  base    = "myapp"
  command = "bash -lc 'echo Building with API_BASE=$API_BASE && npm ci && npm run build'"
  publish = "dist"

[build.environment]
  API_BASE = ""   # left blank here; actual value comes from the Netlify UI

[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy        = "no-referrer"
  X-Frame-Options        = "DENY"
