# Netlify build config for the frontend
[build]
  base    = "myapp"                 # run build from ./myapp
  command = "npm install && npm run build"
  publish = "dist"                  # <-- relative to base (NOT myapp/dist)

[build.environment]
  # Set this in Netlify UI to your Render API URL (e.g., https://pyreactx-api.onrender.com)
  API_BASE = ""

# Optional headers
[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy        = "no-referrer"
  X-Frame-Options        = "DENY"
